### ISSUE TITLE
crawler error: object of type 'NoneType' has no len() http://example

### ISSUE THREAD

**Issue by himanshuraja** [epsylon/xsser#21]
File "/usr/local/lib/python2.7/dist-packages/XSSer/crawler.py", line 217, in _emergency_parse
    data_len = len(html_data)
crawler error: object of type 'NoneType' has no len() http://example

**Comment by epsylon** [comment]
Did you tryed to crawler a target url: http://example ?

**Comment by himanshuraja** [comment]
No actually I am not disclosing it,I know how to use that tool but this time it is giving this error.

**Comment by epsylon** [comment]
Of course this is not a correct exit for program flow. 
But I am asking you, from where comes that http://example url?. 
This is not included on any part of code. That was introduced by you, isn't ?. 
So, is normal that the crawler cannot works properly with an incomplete url. 
Did your tried with others?

**Comment by epsylon** [comment]
File "/usr/local/lib/python2.7/dist-packages/XSSer/crawler.py", line 217, in _emergency_parse
data_len = len(html_data)
crawler error: object of type 'NoneType' has no len()

That means that the crawler is not providing any data to len() and the exit to that is not correctly parsed. This is strange, because crawler should jump to next request after fail.

Did something wrong happens during execution?. Did you tried again?. It is happening always you try?. It is happening with all your targets?.

I see that you are using python 2.7.x... Which version is?. Which OS are you using?

You can add --verbose to have more info about what's going on and paste here (trying to remove real info about your target) the results. 

Also you can edit main.py and change DEBUG=0 to DEBUG=1 so you will have more detailed data about error.

Let me know if you fix it.
