### ISSUE TITLE
Unable to pass --payload command correctly

### ISSUE THREAD

**Issue by flyingorange7** [epsylon/xsser#30]
Hello,
I've been trying to use the --payload command on mutillidae's DNS lookup page.
I already know (by manual injection) that <script> alert("text") </script> should work.
but while passing it through --payload="<script> alert("text") </script>" 
the XSSer tries **http://192.168.2.9/mutillidae/index.php?page=dns-lookup.php/<script>alert('hashed value')</script>**
My intended response was rather http://192.168.2.9/mutillidae/index.php?page=dns-lookup.php/ *">* <script>alert('hashed value')</script>
The URL (in bold) is a failed injection while the one below is a successful one.
How do I get it to work?
my exact command was:
xsser -u "http://192.168.2.9/mutillidae/index.php?page=dns-lookup.php" --payload="<script> alert("text") </script">
i also tried adding --no-head as suggested in other issues previously.
look forward to your response.
Thanks!
EDIT: Haven't updated XSSer in 3-4 weeks is that the issue? will update and confirm the same

**Comment by epsylon** [comment]
Not easy to read your example that way. Try using "code" tag next time to have a more clean format.
Independiently, take this tip:
  1 - XSS (and vector, payload...) are Keywords. That means that if you use it on your manual injections, some special changes will happen after that. XSS keyword is changed by a hash. Only numerical or a md5, depending on your settings (your requirement).

When launching a manual payload that hash special chars, take care on using " and ' when spelling because are interpreted as "open/close" tags.

So: **--payload="<script>alert('XSS');</script>"** is a clean method to distinguish, payload from vector.

What means 'My intended response ' for you?.

Issue working with --no-head (SSL related) has been fixed on latest commit.

**Comment by epsylon** [comment]
EDIT: Haven't updated XSSer in 3-4 weeks is that the issue? will update and confirm the same -> Well, Keywords also are working better from latest commit so... try it again and we review your issue.
Thanks for your report.

**Comment by flyingorange7** [comment]
Hello,
Thanks for the response, I am a new user, my apologies for the inconvenience.
I want a pop - up to appear on my screen to show details of the cookie
So ideally to do so my URL must look like so:
`http://192.168.2.9/mutillidae/index.php?page=dns-lookup.php/"><script>alert(document.cookie);</script>`
This was my command passed:
`xsser -u "http://192.168.2.9/mutillidae/index.php?page=dns-lookup.php" --payload="<script>alert(document.cookie);</script>"`

XSSer tried to attack the following URL when this command was passed:
`http://192.168.2.9/mutillidae/index.php?page=dns-lookup.php/<script>alert(document.cookie);</script>`
The above URL does not have `">` tag after `dns-lookup.php/`
Therefore intended attack is not done correctly and "No XSS vulnerability found" message is given.
To verify the same, I passed the first URL directly and got the expected answer (alert message with details of the cookie)

Look forward to your response.
Thanks

**Comment by epsylon** [comment]
The above URL does not have "> tag after dns-lookup.php/ -> because you aren't spelling it on your manual payload:
xsser -u "http://192.168.2.18/mutillidae/index.php?page=dns-lookup.php" --payload="<script>alert(document.cookie);</script>"
You should try:
xsser -u "http://192.168.2.18/mutillidae/index.php?page=dns-lookup.php" --payload='"><script>alert(document.cookie);</script>'
I am using " for vector (classic one when not manual payload launch) and ' for payload, to close correctly that script on the command line. Do you see what I mean?

**Comment by epsylon** [comment]
OK, you edited. I see, you also checked to include "> on payload, right?.
Lets try to debug a bit more. Try launch with -v to see how HTTP are built. Also sounds intersting if you can run a transparent proxy, so we can see also how injection is made.

**Comment by epsylon** [comment]
Another TIP. You are mixing cookies, with 'XSS' alerts, etc... Well, normally you can exploit all this scenarios (some other users have used XSSer against that app that you are using, so I know a bit server side), but sometimes, you only can use numbers (for examples). It is nice when reporting always to go ahead with same example and don't enter to much variables during it. ;-)

**Comment by flyingorange7** [comment]
Hello epsylon, I apologize for the delay.
As suggested I did use -v, but except for few additional details regarding the session, I could not find anything about how the HTTP was constructed.
I'm afraid I'm still facing the same problem.
![virtualbox_kali linux_13_06_2018_14_47_21](https://user-images.githubusercontent.com/40027485/41342041-e4dfaad8-6f18-11e8-8e1e-a25933afb32d.png)
![virtualbox_kali linux_13_06_2018_14_47_45](https://user-images.githubusercontent.com/40027485/41342055-eac6f9ba-6f18-11e8-89d7-31a80ddf169d.png)
![virtualbox_kali linux_13_06_2018_14_48_07](https://user-images.githubusercontent.com/40027485/41342063-ee9f17fc-6f18-11e8-96a1-49fb7cef4f7e.png)

**Comment by epsylon** [comment]
> I could not find anything about how the HTTP was constructed.
You need try a transparent proxy (burp, polipo, etc..) to intercept/analize HTTP requests.
Look how other users are using it for debugging tasks:
https://github.com/epsylon/xsser/issues/28
