### ISSUE TITLE
Should switch to Python 3

### ISSUE THREAD

**Issue by sbrun** [epsylon/xsser#39]
Hello,

Python 2.x will no longer be supported by their upstream developers in 2020. Thus Debian developers are actively removing Python 2 support in Debian Testing with the goal of getting rid of Python 2 in Debian 11 (bullseye).
Kali is tracking Debian Testing and is thus affected by this. You should consider to switch xsser to Python 3.

FWIW this is tracked in https://gitlab.com/kalilinux/packages/xsser/issues/1 on the Kali side.

**Comment by epsylon** [comment]
Yep, I know that this is an important question to be solved and not only for XSSer code. But, I have found some reasons (I will try to write about it more closely to that dates) when using Python 3, to keep coding on Python 2.7/8 and not make the jump yet... So, I need to think more about it..

Btw, many thanks for your suggestion.

**Comment by epsylon** [comment]
roger! https://gitlab.com/kalilinux/packages/xsser/issues/1#note_220484852

**Comment by epsylon** [comment]
Python 2 was published in 2000, **signalling a more transparent and inclusive language development process**. It included many more programmatic features and added more features throughout its development.

Python 3 is regarded as the future of Python and is the version of the language that is currently in development. Released in late 2008, Python 3 addressed and amended intrinsic design flaws. However, **Python 3 adoption has been slow due to the language not being backwards compatible with Python 2**.

Python 2.7 was published in 2010 as the last of the 2.x releases. The intention behind Python 2.7 was to make it easier for Python 2.x users to port features over to Python 3 by providing some measure of compatibility between the two.

**Comment by epsylon** [comment]
@sbrun XSSer-Python3.x porting level: 90%

**Comment by epsylon** [comment]
@sbrun XSSer has been correctly ported to Python3.x (after some "fight" with gdk, cairo, etc... ), hehe...

Next release (v1.8.2) will be published soon and compatible (with geomapping included) with Kali/Linux.

**Comment by epsylon** [comment]
@sbrun XSSer is now supporting Python3: https://github.com/epsylon/xsser/commit/04a498e6a7e3cc0fea38a5d9172c7a04f136c4bc
